"""
URL configuration for familypro project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from.import views as v
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',v.home),
    path('mens',v.mens_collection),
    path('women',v.women_collection),
    path('electronics',v.electronic_collection),
    path('gym',v.gym_view),
    path('school',v.school_view),
    path('books',v.book_view),
    path('perfumes',v.perfume_view),
    path('cosmetics',v.cosmetic_view),
    path('weapons',v.weapon_view),
    path('accessories',v.accessories_view),
    path('shirt',v.shirt_view),
    path('kudta',v.kudta_view),
    path('oversize',v.oversize_view),
    path('sweatb',v.sweatb_views),
    path('hoodiesb',v.hoodiesb_view),
    path('shervani',v.shervani_view),
    path('jackets',v.jackets_view),
    path('jeans',v.jeans_view),
    path('shorts',v.shorts_view),
    path('cargo',v.cargo_view),
    path('chinos',v.chinos_view),
    path('joggers',v.joggers_view),
    path('cordouary',v.cordouary_view),
    path('sweatp',v.sweatp_views),
    path('tshirts',v.tshirts_view),
    path('hoodiesg',v.hoodiesg_view),
    path('tank',v.tank_view),
    path('peplum',v.peplum_view),
    path('crop',v.crop_view),
    path('cardigans',v.cardigans_view),
    path('tube',v.tube_view),
    path('jeansg',v.jeansg_view),
    path('shortsg',v.shortsg_view),
    path('trouser',v.trouser_view),
    path('skirts',v.skirts_view),
    path('jogger',v.jogger_view),
    path('chinosg',v.chinosg_view),
    path('flare',v.flare_view),
    path('phone',v.phone_view),
    path('swatch',v.swatch_view),
    path('airpods',v.airpods_view),
    path('mvave',v.mvave_view),
    path('camera',v.camera_view),
    path('tv',v.tv_view),
    path('light',v.light_view),
    path('fans',v.fans_view),
    path('charger',v.charger_view),
    path('vc',v.vc_view),
    path('dumbell',v.dumbell_view),
    path('bars',v.bars_view),
    path('hgrip',v.hgrip_view),
    path('creatine',v.creatine_view),
    path('protien',v.protien_view),
    path('gbag',v.gbag_view),
    path('towels',v.towels_view),
    path('shoes',v.shoes_view),
    path('matt',v.matt_view),
    path('wm',v.wm_view),
    path('pens',v.pens_view),
    path('pencil',v.pencil_view),
    path('pouch',v.pouch_view),
    path('lbox',v.lbox_view),
    path('sanitizer',v.sanitizer_view),
    path('sbags',v.sbags_view),
    path('wallets',v.wallets_view),
    path('umb',v.umb_view),
    path('note',v.note_view),
    path('wbottles',v.wbottles_view),
    path('novel',v.novel_view),
    path('sstories',v.sstories_view),
    path('thriller',v.thriller_view),
    path('romance',v.romance_view),
    path('fantasy',v.fantasy_view),
    path('historical',v.historical_view),
    path('cook',v.cook_view),
    path('drama',v.drama_view),
    path('self',v.self_view),
    path('travel',v.travel_view),
    path('eau',v.eau_view),
    path('de',v.de_view),
    path('oil',v.oil_view),
    path('solid',v.solid_view),
    path('splash',v.splash_view),
    path('neutral',v.neutral_view),
    path('seasonal',v.seasonal_view),
    path('gourmand',v.gourmand_view),
    path('wood',v.wood_view),
    path('niche',v.niche_view),
    path('skincare',v.skincare_view),
    path('makeup',v.makeup_view),
    path('haircare',v.haircare_view),
    path('nailcare',v.nailcare_view),
    path('fragnance',v.fragnance_view),
    path('organic',v.organic_view),
    path('mature',v.mature_view),
    path('suncare',v.suncare_view),
    path('lip',v.lip_view),
    path('hair',v.hair_view),
    path('handgun',v.handgun_view),
    path('sniper',v.sniper_view),
    path('shotgun',v.shotgun_view),
    path('daggers',v.dagger_view),
    path('bows',v.bows_view),
    path('nunchaku',v.nunchaku_view),
    path('katana',v.katana_view),
    path('war',v.war_view),
    path('stun',v.stun_view),
    path('whips',v.whips_view),
    path('jewelery',v.jewelery_view),
    path('watch',v.watch_view),
    path('hats',v.hats_view),
    path('eyewear',v.eyewear_view),
    path('scarves',v.scarves_view),
    path('handbags',v.handbags_view),
    path('belts',v.belts_view),
    path('mittens',v.mittens_view),
    path('haira',v.haira_view),
    path('socks',v.socks_view),
    path('shirtcart/<str:p_name>',v.shirt_cart),
    path('kudtacart/<str:p_name>',v.kudta_cart),
    path('oversizecart/<str:p_name>',v.oversize_cart),
    path('sweatb/<str:p_name>',v.sweatb_cart),
    path('hoodiesb/<str:p_name>',v.hoodiesb_cart),
    path('shervanicart/<str:p_name>',v.shervani_cart),
    path('jacketcart/<str:p_name>',v.jacket_cart),
    path('jeansb/<str:p_name>',v.jeans_cart),
    path('shortsbcart/<str:p_name>',v.shortsb_cart),
    path('cargocart/<str:p_name>',v.cargo_cart),
    path('chinosbcart/<str:p_name>',v.chinos_cart),
    path('joggerbcart/<str:p_name>',v.joggerb_cart),
    path('cordouarycart/<str:p_name>',v.cordouary_cart),
    path('sweatpcart/<str:p_name>',v.sweatpants_cart),
    path('tshirtcart/<str:p_name>',v.tshirt_cart),
    path('hoodiesgcart/<str:p_name>',v.hoodiesg_cart),
    path('tankcart/<str:p_name>',v.tank_cart),
    path('peplumcart/<str:p_name>',v.peplum_cart),
    path('cropcart/<str:p_name>',v.crop_cart),
    path('cardigancart/<str:p_name>',v.cardigan_cart),
    path('tubecart/<str:p_name>',v.tube_cart),
    path('jeansgcart/<str:p_name>',v.jeansg_cart),
    path('shortsgcart/<str:p_name>',v.shortsg_cart),
    path('trousercart/<str:p_name>',v.trouser_cart),
    path('skirtscart/<str:p_name>',v.skirt_cart),
    path('joggergcart/<str:p_name>',v.joggerg_cart),
    path('chinosgcart/<str:p_name>',v.chinosg_cart),
    path('flarepantscart/<str:p_name>',v.flarepants_cart),
    path('phonecart/<str:p_name>',v.phone_cart),
    path('swatchcart/<str:p_name>',v.swatch_cart),
    path('airpodscart/<str:p_name>',v.airpods_cart),
    path('mwavecart/<str:p_name>',v.mwave_cart),
    path('cameracart/<str:p_name>',v.camera_cart),
    path('tvcart/<str:p_name>',v.tv_cart),
    path('lightcart/<str:p_name>',v.light_cart),
    path('fanscart/<str:p_name>',v.fans_cart),
    path('chargercart/<str:p_name>',v.charger_cart),
    path('vccart/<str:p_name>',v.vc_cart),
    path('dumbellcart/<str:p_name>',v.dumbell_cart),
    path('barcart/<str:p_name>',v.bar_cart),
    path('hgripcart/<str:p_name>',v.hgrip_cart),
    path('creatinecart/<str:p_name>',v.creatine_cart),
    path('protiencart/<str:p_name>',v.protien_cart),
    path('gbagcart/<str:p_name>',v.gbag_cart),
    path('towelcart/<str:p_name>',v.towel_cart),
    path('shoescart/<str:p_name>',v.shoes_cart),
    path('mattcart/<str:p_name>',v.matt_cart),
    path('wmachinecart/<str:p_name>',v.wmachine_cart),
    path('pencart/<str:p_name>',v.pen_cart),
    path('pencilcart/<str:p_name>',v.pencil_cart),
    path('pouchcart/<str:p_name>',v.pouch_cart),
    path('lboxcart/<str:p_name>',v.lbox_cart),
    path('sanitizercart/<str:p_name>',v.sanitizer_cart),
    path('sbagcart/<str:p_name>',v.sbag_cart),
    path('walletcart/<str:p_name>',v.wallet_cart),
    path('umbrellacart/<str:p_name>',v.umbrella_cart),
    path('notecart/<str:p_name>',v.notebook_cart),
    path('wbottlecart/<str:p_name>',v.wbottle_cart),
    path('novelcart/<str:p_name>',v.novel_cart),
    path('sstoriescart/<str:p_name>',v.sstories_cart),
    path('thrillercart/<str:p_name>',v.thriller_cart),
    path('romancecart/<str:p_name>',v.romance_cart),
    path('fantasycart/<str:p_name>',v.fantasy_cart),
    path('historicalcart/<str:p_name>',v.historical_cart),
    path('cookcart/<str:p_name>',v.cook_cart),
    path('dramacart/<str:p_name>',v.drama_cart),
    path('selfcart/<str:p_name>',v.self_cart),
    path('travelcart/<str:p_name>',v.travel_cart),
    path('eaufcart/<str:p_name>',v.eauf_cart),
    path('eaudcart/<str:p_name>',v.eaud_cart),
    path('oilcart/<str:p_name>',v.oil_cart),
    path('solidcart/<str:p_name>/', v.solid_cart),
    path('splashcart/<str:p_name>',v.splash_cart),
    path('neutralcart/<str:p_name>',v.neutral_cart),
    path('seasonalcart/<str:p_name>',v.seasonal_cart),
    path('gourmandcart/<str:p_name>',v.gourmand_cart),
    path('woodcart/<str:p_name>',v.wood_cart),
    path('nichecart/<str:p_name>',v.niche_cart),
    path('skincarecart/<str:p_name>',v.skincare_cart),
    path('makeupcart/<str:p_name>',v.makeup_cart),
    path('haircarecart/<str:p_name>',v.haircare_cart),
    path('nailcarecart/<str:p_name>',v.nailcare_cart),
    path('fragnancecart/<str:p_name>',v.fragnance_cart),
    path('organiccart/<str:p_name>',v.organic_cart),
    path('maturecart/<str:p_name>',v.mature_cart),
    path('suncarecart/<str:p_name>',v.suncare_cart),
    path('lipcarecart/<str:p_name>',v.lipcare_cart),
    path('hairdyecart/<str:p_name>',v.hairdye_cart),
    path('handguncart/<str:p_name>',v.handgun_cart),
    path('snipercart/<str:p_name>',v.sniper_cart),
    path('shotguncart/<str:p_name>',v.shotgun_cart),
    path('daggercart/<str:p_name>',v.dagger_cart),
    path('bowscart/<str:p_name>',v.bows_cart),
    path('nunchakucart/<str:p_name>',v.nunchaku_cart),
    path('katanacart/<str:p_name>',v.katana_cart),
    path('warhammercart/<str:p_name>',v.warhammer_cart),
    path('stunguncart/<str:p_name>',v.stungun_cart),
    path('whipscart/<str:p_name>',v.whips_cart),
    path('jewelerycart/<str:p_name>',v.jewelery_cart),
    path('watchcart/<str:p_name>',v.watch_cart),
    path('hatscart/<str:p_name>',v.hats_cart),
    path('eyewearcart/<str:p_name>',v.eyewear_cart),
    path('scarvescart/<str:p_name>',v.scarves_cart),
    path('handbagcart/<str:p_name>',v.handbag_cart),
    path('beltscart/<str:p_name>',v.belts_cart),
    path('mittenscart/<str:p_name>',v.mittens_cart),
    path('hairacart/<str:p_name>',v.haira_cart),
    path('sockscart/<str:p_name>',v.socks_cart),
    path('mostbuyedcart/<str:p_name>',v.most_cart),
    path('cartlist',v.cartlist_view),
    path('register',v.register_view,name='register_view'),
    path('login',v.login_view),
    path('logout',v.logout_view),
    path('update/<int:cid>/<str:action>',v.update_quantity),
    path('payment_page/', v.payment_page, name='payment_page'),
    path('payment_page/success/', v.success_view, name='success'),
    path('search_result',v.search_view,name='search_result'),
    path('tcart/<str:p_name>',v.trending_cart),
    path('buy_all', v.buy_all,name='buy_all'),
    path('checkout_confirm/<int:order_id>/', v.checkout_confirm, name='checkout_confirm'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




