# Generated by Django 4.2.7 on 2023-12-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'Trending_category',
            },
        ),
        migrations.CreateModel(
            name='Trending_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='familygo/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familygo.category')),
            ],
            options={
                'db_table': 'Trending_product',
            },
        ),
    ]
