# Generated by Django 4.2.7 on 2023-12-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0003_trending_category_trending_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familygo.trending_product'),
        ),
        migrations.AlterField(
            model_name='trending_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familygo.trending_category'),
        ),
    ]
