# Generated by Django 4.2.7 on 2023-12-31 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0006_airpods_category_airpods_product_bars_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fragnance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.fragnance_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='haircare',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.haircare_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='hairdye',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.hairdye_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='lipcare',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.lipcare_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='makeup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.makeup_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='mature',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.mature_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='nailcare',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.nailcare_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='organic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.organic_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='skincare',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.skincare_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='suncare',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.suncare_product'),
        ),
    ]
