# Generated by Django 4.2.7 on 2023-12-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0007_cart_fragnance_cart_haircare_cart_hairdye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.bows_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='dagger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.dagger_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='handgun',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.handgun_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='katana',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.katana_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='nunchaku',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.nunchaku_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shotgun',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.shotgun_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='sniper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.sniper_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='stungun',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.stungun_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='warhammer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.warhammer_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='whips',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.whips_product'),
        ),
    ]
