# Generated by Django 4.2.7 on 2023-12-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0008_cart_bow_cart_dagger_cart_handgun_cart_katana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='belts',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.belts_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='eyewear',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.eyewear_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='haira',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.hairaccessories_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='handbag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.handbag_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='hats',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.hats_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='jewelery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.jewelery_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='mittens',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.mittens_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='scarves',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.scarves_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='socks',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.socks_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='watch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.watch_product'),
        ),
    ]
