# Generated by Django 4.2.7 on 2024-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0009_cart_belts_cart_eyewear_cart_haira_cart_handbag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
        ),
    ]
