# Generated by Django 4.2.7 on 2024-01-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0011_buy_delete_otherproductcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kudta_product',
            old_name='k_name',
            new_name='p_name',
        ),
    ]
