# Generated by Django 4.2.7 on 2024-01-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familygo', '0012_rename_k_name_kudta_product_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tcart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='familygo.trending_product'),
        ),
    ]
